### ISSUE TITLE
[DS] resize & crop 리서치 

### ISSUE THREAD

**Issue by kimdoeon** [FLYAI4/super-resolution#1]
### 📌 Description
resize와 crop을 위한 리서치

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- crop 방법 정하기
- resize 리서치
<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [ ] [locating&recognizing painting in gallery](https://github.com/nating/recognizing-paintings)
   - [ ] 작동 확인
   - [ ] 파이썬 코드로 변환?
- [ ] [VCS-painting](https://github.com/roberto-amoroso/VCS-painting-recognition/tree/master)
   - [ ] 작동 확인
